<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Sales.aspx.cs" Inherits="webApp.Sales" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <style>
        /* Animación de fondo */
        @keyframes colorChange {
            0% {
                background-color: #f0f2f5;
            }
            25% {
                background-color: #e3f2fd;
            }
            50% {
                background-color: #fff3e0;
            }
            75% {
                background-color: #e8f5e9;
            }
            100% {
                background-color: #f0f2f5;
            }
        }

        body {
            animation: colorChange 10s infinite;
            background-color:blueviolet;
            transition: background-color 1s ease;
        }

        /* Contenedor del carrito */
        .cart-container {
            max-width: 900px;
            margin: 40px auto;
            background-color:#0D1B2A;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
        }

        /* Encabezado */
        h2 {
            color: #343a40;
            font-weight: bold;
            text-align: center;
            margin-bottom: 30px;
        }

        /* Título de la sección */
        .section-title {
            font-weight: bold;
            font-size: 1.3em;
            margin-bottom: 15px;
            color: white;
        }

        /* Elementos del carrito */
        .cart-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 15px 0;
            border-bottom: 1px solid #dee2e6;
        }

        .cart-item:last-child {
            border-bottom: none;
        }

        .cart-item-details p {
            margin: 0;
            color:  white;
        }

        /* Botón de eliminar con animación de color */
        .cart-item button {
            border: none;
            background-color: #dc3545;
            color: white;
            padding: 6px 12px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease-in-out;
        }

        .cart-item button:hover {
            background-color: #c82333;
        }

        /* Campos del formulario */
        .form-group label {
            font-weight: bold;
            color:white;
        }

        .form-check-label {
            font-weight: 500;
            color:white;
        }

        /* Botón principal con animación de color */
        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
            padding: 10px 30px;
            font-size: 1.1em;
            border-radius: 5px;
            transition: background-color 0.3s ease-in-out;
        }

        .btn-primary:hover {
            background-color: #0056b3;
        }

        /* Animación de los botones de aplicar cupón */
        .apply-coupon button {
            background-color: #28a745;
            color: white;
            border: none;
            padding: 6px 12px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease-in-out;
        }

        .apply-coupon button:hover {
            background-color: #218838;
        }

        /* Estilos para los inputs de cupón */
        .apply-coupon input[type="text"] {
            width: 200px;
            margin-right: 10px;
            padding: 6px 12px;
            border: 1px solid #ced4da;
            border-radius: 5px;
        }


.btnApply {
  background-color: #b81515;
  padding: 7px;
  width: 100px;
  font-family: Verdana, Geneva, Tahoma, sans-serif;
  animation: bn53bounce 4s infinite;
  cursor: pointer;
}

/*ANIMACION PARA TITULO DEL CARRITO*/
.tracking-in-expand {
	-webkit-animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
	        animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-10-22 21:19:52
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-expand
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}
@keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}

/**/
@keyframes bn53bounce {
  5%,
  50% {
    transform: scale(1);
  }

  10% {
    transform: scale(1);
  }

  15% {
    transform: scale(1);
  }

  20% {
    transform: scale(1) rotate(-5deg);
  }

  25% {
    transform: scale(1) rotate(5deg);
  }

  30% {
    transform: scale(1) rotate(-3deg);
  }

  35% {
    transform: scale(1) rotate(2deg);
  }

  40% {
    transform: scale(1) rotate(0);
  }
}

.bn39 {
  background-image: linear-gradient(135deg, #008aff, #86d472);
  border-radius: 6px;
  box-sizing: border-box;
  color: #ffffff;
  display: block;
  height: 50px;
  font-size: 1.4em;
  font-weight: 600;
  padding: 4px;
  position: relative;
  text-decoration: none;
  width: 7em;
  z-index: 2;


}
    /*boton confrm orden*/
.bn5 {
  padding: 0.6em 2em;
  border: none;
  outline: none;
  color: rgb(255, 255, 255);
  background: #111;
  cursor: pointer;
  position: relative;
  z-index: 0;
  border-radius: 10px;
}

.bn5:before {
  content: "";
  background: linear-gradient(
    45deg,
    #ff0000,
    #ff7300,
    #fffb00,
    #48ff00,
    #00ffd5,
    #002bff,
    #7a00ff,
    #ff00c8,
    #ff0000
  );
  position: absolute;
  top: -2px;
  left: -2px;
  background-size: 400%;
  z-index: -1;
  filter: blur(5px);
  width: calc(100% + 4px);
  height: calc(100% + 4px);
  animation: glowingbn5 20s linear infinite;
  opacity: 0;
  transition: opacity 0.3s ease-in-out;
  border-radius: 10px;
}

@keyframes glowingbn5 {
  0% {
    background-position: 0 0;
  }
  50% {
    background-position: 400% 0;
  }
  100% {
    background-position: 0 0;
  }
}

.bn5:active {
  color: #000;
}

.bn5:active:after {
  background: transparent;
}

.bn5:hover:before {
  opacity: 1;
}

.bn5:after {
  z-index: -1;
  content: "";
  position: absolute;
  width: 100%;
  height: 100%;
  background: #191919;
  left: 0;
  top: 0;
  border-radius: 10px;
}

.bn6 {
  cursor: pointer;
  padding: 0.2em 1em;
  outline: none;
  border: none;
  background-color: #232423;
  border-radius: 30px;
  font-size: 1.4em;
  font-weight: 600;
  color: #ffffff;
  background-size: 100% 100%;
  box-shadow: 0 0 0 4px #232423 inset;

}


.bn6:hover {
  background-image: linear-gradient(
    55deg,
    transparent 10%,
    #161616 10% 20%,
    transparent 20% 30%,
    #161616 30% 40%,
    transparent 40% 50%,
    #161616 50% 60%,
    transparent 60% 70%,
    #161616 70% 80%,
    transparent 80% 90%,
    #161616 90% 100%
  );
  animation: background 3s linear infinite;
}


    </style>
    <div class="cart-container">
        <h2 class="tracking-in-expand" style="color: white;">Shopping Cart</h2> 
        <!-- Sección de Artículos en el Carrito -->
        <div class="section-title">Items in Cart</div>

        <!-- Artículo 1 -->
        <div class="cart-item">
            <div class="cart-item-details">
                <p><strong>ID:</strong> </p>
                <p><strong>Name:</strong></p>
                <p><strong>Size:</strong></p>
                <p><strong>Color:</strong> </p>
                <p><strong>Brand:</strong> </p>
                <p><strong>Category:</strong> </p>
                    <p><strong>Price:</strong></p>
            </div>
            <button>Delete</button>
        </div>

        <!-- Artículo 2 -->
        <div class="cart-item">
            <div class="cart-item-details">
                <p><strong>ID:</strong> </p>
                <p><strong>Name:</strong> </p>
                <p><strong>Size:</strong></p>
                <p><strong>Color:</strong> </p>
                <p><strong>Brand:</strong></p>
                <p><strong>Category:</strong> </p>
                <p><strong>Price:</strong></p>
            </div>
            <button>Delete</button>
        </div>

        <!-- Opción para aplicar cupón -->
        <div class="apply-coupon">
            <input type="text" id="couponCode" placeholder="Apply discount">
            <button class="btnApply">Apply</button>
        </div>

        <!-- Sección de Datos de Envío -->
        <div class="section-title">Shipping Data</div>
        <form>
            <div class="form-group">
                <label for="nombre">Name</label>
                <input type="text" class="form-control" id="nombre" placeholder="Name" required>
            </div>
           <div class="form-group">
         <label for="nombre">Last name</label>
         <input type="text" class="form-control" id="txtLastName" placeholder="Last Name" required>
            </div>
            <div class="form-group">
                <label for="Address">Address</label>
                <input type="text" class="form-control" id="direccion" placeholder="Address" required>
            </div>
            <div class="form-group">
                <label for="telefono">Phone</label>
                <input type="tel" class="form-control" id="telefono" placeholder="Contact phone" required>
            </div>
            <div class="form-group">
                <label for="numeroEnvio">Zip Code</label>
                <input type="text" class="form-control" id="numeroEnvio" placeholder="Zip code" required>
            </div>
        </form>

        <!-- Sección de Métodos de Pago -->
        <div class="section-title">Payment Methods</div>
        <form>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="pago" id="tarjetaCredito" value="credito" checked>
                <label class="form-check-label" for="tarjetaCredito">
                    Credit card
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="pago" id="paypal" value="paypal">
                <label class="form-check-label" for="paypal">
                    PayPal
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="pago" id="transferencia" value="transferencia">
                <label class="form-check-label" for="transferencia">
                    Bank Transfer
                </label>
            </div>
        </form>

        <!-- Sección de Método de Envío -->
        <div class="section-title">Shipping Method</div>
        <form>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="envio" id="envioCorreo" value="correo" checked>
                <label class="form-check-label" for="envioCorreo">
                   Shipping by Mail
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="envio" id="retiroLocal" value="retiro">
                <label class="form-check-label" for="retiroLocal">
                   Local Pickup
                </label>
            </div>
        </form>

        <!-- Botón de Confirmar Compra -->
        <div class="mt-4 text-center">
            <button class="bn5">Confirm Order</button>
            <button class="bn6">Cancel</button>
        </div>
    </div>
</asp:Content>
